// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ParentFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw-7Z2M2LXyCu2Bnr0KG8apdjeEodQML0',
    appId: '1:698194712327:web:b76e0eebf29148466a97a2',
    messagingSenderId: '698194712327',
    projectId: 'techpek-bd',
    authDomain: 'techpek-bd.firebaseapp.com',
    databaseURL: 'https://techpek-bd-default-rtdb.firebaseio.com',
    storageBucket: 'techpek-bd.firebasestorage.app',
    measurementId: 'G-Z9WDSYRK40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv3K08QNghYAVhIt5Z4zDCScTGom6WGRc',
    appId: '1:698194712327:android:a968cb64cb31924c6a97a2',
    messagingSenderId: '698194712327',
    projectId: 'techpek-bd',
    databaseURL: 'https://techpek-bd-default-rtdb.firebaseio.com',
    storageBucket: 'techpek-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ6B_6kdNi6lAttcS_O_RZktrgEKMcxZw',
    appId: '1:698194712327:ios:aec86cee62c571606a97a2',
    messagingSenderId: '698194712327',
    projectId: 'techpek-bd',
    databaseURL: 'https://techpek-bd-default-rtdb.firebaseio.com',
    storageBucket: 'techpek-bd.firebasestorage.app',
    iosBundleId: 'com.techpek.flutterDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ6B_6kdNi6lAttcS_O_RZktrgEKMcxZw',
    appId: '1:698194712327:ios:aec86cee62c571606a97a2',
    messagingSenderId: '698194712327',
    projectId: 'techpek-bd',
    databaseURL: 'https://techpek-bd-default-rtdb.firebaseio.com',
    storageBucket: 'techpek-bd.firebasestorage.app',
    iosBundleId: 'com.techpek.flutterDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw-7Z2M2LXyCu2Bnr0KG8apdjeEodQML0',
    appId: '1:698194712327:web:20fbf7374da8fc496a97a2',
    messagingSenderId: '698194712327',
    projectId: 'techpek-bd',
    authDomain: 'techpek-bd.firebaseapp.com',
    databaseURL: 'https://techpek-bd-default-rtdb.firebaseio.com',
    storageBucket: 'techpek-bd.firebasestorage.app',
    measurementId: 'G-2XVZTLD9RY',
  );
}
