// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeliB8fewrqASzhYHBlXh8eat2lgHf6RU',
    appId: '1:680509866471:web:76063bcd03e8c204b6bd42',
    messagingSenderId: '680509866471',
    projectId: 'picon-co',
    authDomain: 'picon-co.firebaseapp.com',
    databaseURL: 'https://picon-co-default-rtdb.firebaseio.com',
    storageBucket: 'picon-co.appspot.com',
    measurementId: 'G-7NYG351LYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDxdzmh7WV4e8661GAMpB16aF3y97vuOk',
    appId: '1:680509866471:android:6b5999ebee170bffb6bd42',
    messagingSenderId: '680509866471',
    projectId: 'picon-co',
    databaseURL: 'https://picon-co-default-rtdb.firebaseio.com',
    storageBucket: 'picon-co.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQtOv9ZqM8pwEtRyJdS5bZcSguac9CZHw',
    appId: '1:680509866471:ios:dc78ee3463b3cda6b6bd42',
    messagingSenderId: '680509866471',
    projectId: 'picon-co',
    databaseURL: 'https://picon-co-default-rtdb.firebaseio.com',
    storageBucket: 'picon-co.appspot.com',
    androidClientId: '680509866471-02q9o6ho9pg0tvbvimbinmvn6oun4cma.apps.googleusercontent.com',
    iosClientId: '680509866471-f28triv3jc5u2mliqmoud1nd4p1omm29.apps.googleusercontent.com',
    iosBundleId: 'com.picon.picon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQtOv9ZqM8pwEtRyJdS5bZcSguac9CZHw',
    appId: '1:680509866471:ios:dc78ee3463b3cda6b6bd42',
    messagingSenderId: '680509866471',
    projectId: 'picon-co',
    databaseURL: 'https://picon-co-default-rtdb.firebaseio.com',
    storageBucket: 'picon-co.appspot.com',
    androidClientId: '680509866471-02q9o6ho9pg0tvbvimbinmvn6oun4cma.apps.googleusercontent.com',
    iosClientId: '680509866471-f28triv3jc5u2mliqmoud1nd4p1omm29.apps.googleusercontent.com',
    iosBundleId: 'com.picon.picon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV6xRkXfnqSRwFeZ8OU2SaNQYcmThvkpE',
    appId: '1:680509866471:web:830fa610e778bba4b6bd42',
    messagingSenderId: '680509866471',
    projectId: 'picon-co',
    authDomain: 'picon-co.firebaseapp.com',
    databaseURL: 'https://picon-co-default-rtdb.firebaseio.com',
    storageBucket: 'picon-co.appspot.com',
    measurementId: 'G-M4W0673TJ7',
  );
}
