// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3fyaWcxTxC9P4x7zikxOoC8DpP7RRnwo',
    appId: '1:916319691429:web:41148e60476fb266d8e34c',
    messagingSenderId: '916319691429',
    projectId: 'kegelx-bd',
    authDomain: 'kegelx-bd.firebaseapp.com',
    databaseURL: 'https://kegelx-bd-default-rtdb.firebaseio.com',
    storageBucket: 'kegelx-bd.firebasestorage.app',
    measurementId: 'G-1E6MKF5597',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh_PSvNqr7sLFc1kIjI8PqVkjY_8Eod3I',
    appId: '1:916319691429:android:37f5d76d2c2154d5d8e34c',
    messagingSenderId: '916319691429',
    projectId: 'kegelx-bd',
    databaseURL: 'https://kegelx-bd-default-rtdb.firebaseio.com',
    storageBucket: 'kegelx-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlV9MJ0Q9YePJhUQquIWB-ENYvDqJNitw',
    appId: '1:916319691429:ios:4f113b54b15dadb1d8e34c',
    messagingSenderId: '916319691429',
    projectId: 'kegelx-bd',
    databaseURL: 'https://kegelx-bd-default-rtdb.firebaseio.com',
    storageBucket: 'kegelx-bd.firebasestorage.app',
    androidClientId:
        '916319691429-mdas88m9bd2im857gmaai5gknoq51cha.apps.googleusercontent.com',
    iosClientId:
        '916319691429-qn44to2iv3cp9l02f0ulkftrbd725f04.apps.googleusercontent.com',
    iosBundleId: 'com.teckpek.kegelx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlV9MJ0Q9YePJhUQquIWB-ENYvDqJNitw',
    appId: '1:916319691429:ios:4f113b54b15dadb1d8e34c',
    messagingSenderId: '916319691429',
    projectId: 'kegelx-bd',
    databaseURL: 'https://kegelx-bd-default-rtdb.firebaseio.com',
    storageBucket: 'kegelx-bd.firebasestorage.app',
    androidClientId:
        '916319691429-mdas88m9bd2im857gmaai5gknoq51cha.apps.googleusercontent.com',
    iosClientId:
        '916319691429-qn44to2iv3cp9l02f0ulkftrbd725f04.apps.googleusercontent.com',
    iosBundleId: 'com.teckpek.kegelx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3fyaWcxTxC9P4x7zikxOoC8DpP7RRnwo',
    appId: '1:916319691429:web:419fc706ea160637d8e34c',
    messagingSenderId: '916319691429',
    projectId: 'kegelx-bd',
    authDomain: 'kegelx-bd.firebaseapp.com',
    databaseURL: 'https://kegelx-bd-default-rtdb.firebaseio.com',
    storageBucket: 'kegelx-bd.firebasestorage.app',
    measurementId: 'G-M7LZXMJ61J',
  );
}
