// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChT8xDB4JdLlxqmx4yepCR1gXcqlvkVAs',
    appId: '1:545857015300:web:9a6915c3f60935d1486f51',
    messagingSenderId: '545857015300',
    projectId: 'picon-bd',
    authDomain: 'picon-bd.firebaseapp.com',
    databaseURL:
    'https://picon-bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'picon-bd.appspot.com',
    measurementId: 'G-804ZGZSHX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDxdzmh7WV4e8661GAMpB16aF3y97vuOk',
    appId: '1:680509866471:android:6b5999ebee170bffb6bd42',
    messagingSenderId: '680509866471',
    projectId: 'picon-co',
    databaseURL: 'https://picon-co-default-rtdb.firebaseio.com',
    storageBucket: 'picon-co.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQtOv9ZqM8pwEtRyJdS5bZcSguac9CZHw',
    appId: '1:680509866471:ios:dc78ee3463b3cda6b6bd42',
    messagingSenderId: '680509866471',
    projectId: 'picon-co',
    databaseURL: 'https://picon-co-default-rtdb.firebaseio.com',
    storageBucket: 'picon-co.appspot.com',
    androidClientId: '680509866471-02q9o6ho9pg0tvbvimbinmvn6oun4cma.apps.googleusercontent.com',
    iosClientId: '680509866471-f28triv3jc5u2mliqmoud1nd4p1omm29.apps.googleusercontent.com',
    iosBundleId: 'com.picon.picon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6AcjpgOq6wjSxYmP8j9YzgC6kwvR2wk',
    appId: '1:545857015300:ios:6a15f766168d3d1a486f51',
    messagingSenderId: '545857015300',
    projectId: 'picon-bd',
    databaseURL:
    'https://picon-bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'picon-bd.appspot.com',
    iosBundleId: 'com.picon.picon.RunnerTests',
  );
}